spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
    password: Kingback666
    driver-class-name: com.mysql.jdbc.Driver
    druid:
#      开启监控内置页面
      stat-view-servlet:
        reset-enable: true
        login-username: admin
        login-password: admin
        enabled: true
#        开启web-jdbc关联监控
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#        监控spring-bean
      aop-patterns: com.billion.boot
#      开启监控和防火墙功能
      filters: stat,wall
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 3
          enabled: true
        wall:
          config:
            delete-allow: false
mybatis:
  mapper-locations: classpath:mybatis/mapper/BookMapper2.xml
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
info:
  compony: Billion
  author: JackAndRose
  appName: @project.groupId@
  appVersion: @project.version@

